-- Server-side sync rate limiting used by the extension sync path.

create table if not exists public.sync_rate_events (
  id bigint generated by default as identity primary key,
  vault_key text not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists sync_rate_events_vault_created_idx
  on public.sync_rate_events (vault_key, created_at desc);

alter table public.sync_rate_events enable row level security;
revoke all on table public.sync_rate_events from anon, authenticated;
revoke all on sequence public.sync_rate_events_id_seq from anon, authenticated;

create or replace function public.check_sync_rate_limit(p_vault_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  minute_count integer;
  hour_count integer;
begin
  if not public.is_relay_vault_key(p_vault_key) then
    return jsonb_build_object('allowed', false, 'reason', 'invalid');
  end if;

  delete from public.sync_rate_events
    where created_at < now() - interval '2 hours';

  select count(*) into minute_count
    from public.sync_rate_events
    where vault_key = p_vault_key
      and created_at >= now() - interval '1 minute';

  if minute_count >= 5 then
    return jsonb_build_object('allowed', false, 'window', 'minute');
  end if;

  select count(*) into hour_count
    from public.sync_rate_events
    where vault_key = p_vault_key
      and created_at >= now() - interval '1 hour';

  if hour_count >= 60 then
    return jsonb_build_object('allowed', false, 'window', 'hour');
  end if;

  insert into public.sync_rate_events (vault_key) values (p_vault_key);
  return jsonb_build_object('allowed', true);
end;
$$;

grant execute on function public.check_sync_rate_limit(text) to anon, authenticated;
